### ISSUE TITLE
关于单条或批量查询检索速度的求助

### ISSUE THREAD

**Issue by tzteyang** [RUC-NLPIR/FlashRAG#135]
在使用官方提供的语料库和索引库以及检索器的默认设置下，并且通过`conda install -c pytorch faiss-cpu=1.8.0`命令安装的faiss，同时并没有使用gpu进行加速，我尝试对一条或一个批量的虚拟查询进行检索速度的测试，我注意到 [https://github.com/RUC-NLPIR/FlashRAG/issues/4](url)在这里官方提供的检索速度参考，这和我现在测试的结果相差很大，现在单条查询的量级都在10s左右，下面是我所使用的机器信息以及检索配置文件内容，我不确定是因为什么造成了这种情况，想求助一下有哪些可能的原因呢？

机器配置
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       HygonGenuine
CPU family:                      24
Model:                           0
Model name:                      Hygon C86 7151 16-core Processor
...
```

检索配置
```
# -------------------------------------------------Retrieval Settings------------------------------------------------#
# If set the name, the model path will be find in global paths
retrieval_method: "e5" # name or path of the retrieval model.
retrieval_model_path: "xxx/models/e5-base-v2" # path to the retrieval model
index_path: "xxx/retrieval_corpus/data00/jiajie_jin/flashrag_indexes/wiki_dpr_100w/e5_flat_inner.index" # set automatically if not provided.
multimodal_index_path_dict: ~ # use for multimodal retreiver, example format: {'text': 'path/to/text_index' or None, 'image': 'path/to/image_index' or None}
faiss_gpu: False # whether use gpu to hold index
corpus_path: xxx/wiki18_100w.jsonl # path to corpus in '.jsonl' format that store the documents

instruction: ~ # instruction for the retrieval model
retrieval_topk: 5 # number of retrieved documents
retrieval_batch_size: 8 # batch size for retrieval
retrieval_use_fp16: True # whether to use fp16 for retrieval model
retrieval_query_max_length: 256 # max length of the query
save_retrieval_cache: False # whether to save the retrieval cache
use_retrieval_cache: False # whether to use the retrieval cache
retrieval_cache_path: ~ # path to the retrieval cache
retrieval_pooling_method: ~ # set automatically if not provided
bm25_backend: bm25s # pyserini, bm25s
use_sentence_transformer: False

use_reranker: False # whether to use reranker
rerank_model_name: ~ # same as retrieval_method
rerank_model_path: ~ # path to reranker model, path will be automatically find in `model2path`
rerank_pooling_method: ~
rerank_topk: 5 # number of remain documents after reranking
rerank_max_length: 512
rerank_batch_size: 256 # batch size for reranker
rerank_use_fp16: True

# If you want to use multi retrievers, you can set the following parameters
use_multi_retriever: False # whether to use multi retrievers
multi_retriever_setting:
  merge_method: "concat" # support 'concat', 'rrf', 'rerank'
  topk: 5 # final remain documents, only used in 'rrf' and 'rerank' merge
  rerank_model_name: ~
  rerank_model_path: ~
  retriever_list:
    - retrieval_method: "e5"
      retrieval_topk: 5
      index_path: ~
      retrieval_model_path: ~
    - retrieval_method: "bm25"
      retrieval_topk: 5
      index_path: ~
      retrieval_model_path: ~
```
